### PR TITLE
new dockerfile comment added

### PR DESCRIPTION
**Pull request by atulj007**
- Read the contribution guidelines
- Include a reference to a related issue in this repository
- A description of the changes proposed in the pull request

### CODE REVIEW

**Review by Joshiatul619 — APPROVED** [review]
approved

**Review by Joshiatul619 — COMMENTED** [review]
approved

**Review by Joshiatul619 — APPROVED** [review]

**Review by Joshiatul619 — APPROVED** [review]

**Review by Joshiatul619 — APPROVED** [review]

**Review by Joshiatul619 — APPROVED** [review]
approved

**Review by atulj007 — COMMENTED** [review]
apprvoed

**Pull request closed without merging**
